# This is a generated file. Not intended for manual editing.
services:
  dotnet.cep:
    build:
      context: "/home/ismael3s/RiderProjects/Dotnet.Cep/src"
      dockerfile: "Dotnet.Cep/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "dotnet.cep:dev"
    ports:
    - "127.0.0.1:57000:57000"
    - "127.0.0.1:57200:57200"
    - "127.0.0.1:57400:57400"
    volumes:
    - "/home/ismael3s/RiderProjects/Dotnet.Cep/src/Dotnet.Cep:/app:rw"
    - "/home/ismael3s/RiderProjects/Dotnet.Cep:/src:rw"
    - "/home/ismael3s/.nuget/packages:/home/app/.nuget/packages"
    - "/home/ismael3s/.local/share/JetBrains/RiderRemoteDebugger/2024.3/Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "/home/ismael3s/Rider/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/home/ismael3s/.cache/JetBrains/Rider2024.3/log/DebuggerWorker/JetBrains.Debugger.Worker.2024_12_29_22_03_28:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
